export const Questions = [
  {
    question: "Which one is correct ?",
    optionA: "I don't have any money. Therefore, I will go shopping.",
    optionB: "I don't have any money. Moreover, I will go shopping.",
    optionC: "I don't have any money. However, I will go shopping.",
    optionD: "I don't have any money. Likewise, I will go shopping.",
    answer: "C",
  },
  {
    question: "Choose the correct option ?",
    optionA: "He loves swimming, running, and to taking yoga classes.",
    optionB: "He loves swimming, running, and taking yoga classes.",
    optionC: "He loves swimming, running, and to take yoga classes.",
    optionD: "He loves swimming, running, and take yoga classes.",
    answer: "B",
  },
  {
    question: "Choose the correct option ?",
    optionA: "We will for her, if she arrives late.",
    optionB: "If she arrives, late we will wait for her.",
    optionC: "If she arrives late we wait for her.",
    optionD: "We will wait for her if she arrives late .",
    answer: "D",
  },
  {
    question: "Choose the correct option ?",
    optionA: "She denied stealing the cell phone.",
    optionB: "She denied to steal the cell phone.",
    optionC: "She denied stealing cell phone.",
    optionD: "She denied to steal cell phone.",
    answer: "A",
  },
  {
    question: "Choose the correct option ?",
    optionA: "The city fixing the park quick.",
    optionB: "The city fixed the park quickly.",
    optionC: "The city fixed the park quick.",
    optionD: "The city fixing the park quickly.",
    answer: "B.",
  },
  {
    question: "Choose the correct option ?",
    optionA: "Although she doesn't like the products, she likes the service.",
    optionB: "Although she doesn't like the products.",
    optionC: "She doesn't like the products, she likes the service.",
    optionD: "She doesn't like the products she likes the service.",
    answer: "A",
  },
  {
    question: "Choose the correct option ?",
    optionA: "The team usually play games on Saturday morning.",
    optionB: "The team usually plays games on Saturday morning.",
    optionC: "The team usually plays games on the Saturday morning.",
    optionD: "The team usually play games on the Saturday morning.",
    answer: "B",
  },
  {
    question: "Choose the correct option ?",
    optionA: "She refuses to work late, to work early, or working at home.",
    optionB: "She refuses to work late, working early, or to work at home.",
    optionC: "She refuses to work late, work early, or work at home.",
    optionD: "She refuses to work late, to work early, or work at home.",
    answer: "C",
  },
  {
    question: "Choose the correct option ?",
    optionA: "Money you gave me was not enough.",
    optionB: "The money you gave me was not enough.",
    optionC: "The money you gave me were not enough.",
    optionD: "Money you gave me was not enough.",
    answer: "B",
  },
  {
    question: "Choose the correct option ?",
    optionA: "They have completed project successful.",
    optionB: "They have completed the project successfully.",
    optionC: "They have completed the project successful.",
    optionD: "They have completed project successfully.",
    answer: "B",
  },
  {
    question: "Choose the correct option ?",
    optionA: "I met a doctor and a police officer at the party.",
    optionB: "I met a Doctor and a Police Officer at the party.",
    optionC: "I met a Doctor and a Police officer in the party.",
    optionD: "I met a Doctor and a police officer at the party.",
    answer: "A",
  },
  {
    question: "Choose the correct option ?",
    optionA: "Due to the heavy rain, the river has becoming flood.",
    optionB: "Due to the heavy rain, the river has become flood.",
    optionC: "Due to the heavy rain, the river has become flooded.",
    optionD: "Due to the heavy rain, the river has become flooding.",
    answer: "C",
  },
  {
    question: "Choose the correct option ?",
    optionA: "Cat has a toy.",
    optionB: "A cat has toy.",
    optionC: "The cats have a toys.",
    optionD: "The cat has a toy.",
    answer: "D",
  },
  {
    question: "Choose the correct option ?",
    optionA: "The most creation presentation was from the second group.",
    optionB: "The most create presentation was from the second group.",
    optionC: "The most creative presentation was from the second group.",
    optionD: "The most creatively presentation was from the second group.",
    answer: "C",
  },
  {
    question: "Choose the correct option ?",
    optionA: "One of the people I met to live in France.",
    optionB: "One of the people I met live in France.",
    optionC: "One of the people I met living in France.",
    optionD: "One of the people I met lives in France.",
    answer: "D",
  },
  {
    question: "Choose the correct option ?",
    optionA: "She received an advices.",
    optionB: "She received the advice.",
    optionC: "She received an advice.",
    optionD: "She received a advice.",
    answer: "B",
  },
  {
    question: "Choose the correct option ?",
    optionA: "Without proper identification: he could not enter the building.",
    optionB: "Without proper identification, he could not enter the building.",
    optionC: "Without proper identification. He could not enter the building.",
    optionD: "Without proper identification; he could not enter the building.",
    answer: "B",
  },
  {
    question: "He drives quite______, but his brother drives really_____ ?",
    optionA: "slow ... fast",
    optionB: "slowly ... fast",
    optionC: "slow ... fastly",
    optionD: "slowly ... fastly",
    answer: "B",
  },
  {
    question: "He____ ever works as____ as he should",
    optionA: "hardly ... hardly",
    optionB: "hardly ... hard",
    optionC: "hard ... hard",
    optionD: "hard ... hardly",
    answer: "B",
  },
  {
    question: "I'd rather you___ to her why we can't go.",
    optionA: "would explain",
    optionB: "explained",
    optionC: "to explain",
    optionD: "will explain",
    answer: "B",
  },
  {
    question: "Can I park here?",
    optionA: "Sorry, I did that.",
    optionB: "It's the same place.",
    optionC: "Only for half an hour",
    optionD: "Only for half hour",
    answer: "C",
  },
  {
    question: "What colour will you paint the children's bedroom?",
    optionA: "I hope it was right.",
    optionB: "We can't decide",
    optionC: "It wasn't very difficult",
    optionD: "No option is right",
    answer: "B",
  },
  {
    question: "I can't understand this email",
    optionA: "Would you like some help?",
    optionB: "Don't you know?",
    optionC: "I suppose you can",
    optionD: "No option is right.",
    answer: "A",
  },
  {
    question: "I'd like two tickets for tomorrow night.",
    optionA: "How much did you play?",
    optionB: "Afternoon and evening.",
    optionC: "I'll just check for you.",
    optionD: "All the option are right.",
    answer: "C",
  },
  {
    question:
      "The company needs to decide ... and for all what its position is on this point",
    optionA: "here",
    optionB: "once",
    optionC: "first",
    optionD: "finally",
    answer: "B",
  },
  {
    question:
      "Don't put your cup on the ... of the table - someone will knock it off.",
    optionA: "outside",
    optionB: "edge",
    optionC: "boundary",
    optionD: "border",
    answer: "B",
  },
  {
    question: "I'm sorry - I didn't... to disturb you.",
    optionA: "hope",
    optionB: "think",
    optionC: "mean",
    optionD: "suppose",
    answer: "C",
  },
  {
    question:
      "Would you mind .... these plates a wipe before putting them in the cupboard?",
    optionA: "making",
    optionB: "doing",
    optionC: "getting",
    optionD: "giving",
    answer: "D",
  },
  {
    question:
      "I was looking forward ... at the new restaurant, but is was closed.",
    optionA: "to eat",
    optionB: "to have eaten",
    optionC: "to eating",
    optionD: "eating",
    answer: "C",
  },
  {
    question:
      "The shop didn't have the shoes I wanted, but they've ... a pair specially for me.",
    optionA: "booked",
    optionB: "ordered",
    optionC: "commanded",
    optionD: "asked",
    answer: "B",
  },
  {
    question:
      "Have you got time to discuss your work now or are you ... to leave?",
    optionA: "thinking",
    optionB: "round",
    optionC: "planned",
    optionD: "about",
    answer: "D",
  },
  {
    question:
      "Once the plane is in the air, you can ... your seat belts if you wish.",
    optionA: "undress",
    optionB: "unfasten",
    optionC: "unlock",
    optionD: "untie",
    answer: "B",
  },
  {
    question: "You can't smoke here - please _____ cigarette.",
    optionA: "put away",
    optionB: "put up with",
    optionC: "put down",
    optionD: "put out",
    answer: "D",
  },
  {
    question: "He's so ___! I'm not___ in anything he says.",
    optionA: "boring...interesting",
    optionB: "bored... interesting",
    optionC: "bored...interested",
    optionD: "boring...interested",
    answer: "D",
  },
  {
    question:
      "Every time I wear something white, I ____ coffee or a orange juice or something on it.",
    optionA: "spill",
    optionB: "let",
    optionC: "drop",
    optionD: "pour",
    answer: "A",
  },
  {
    question: "Her hair isn't completely straight____",
    optionA: "waved",
    optionB: "wavy",
    optionC: "curl",
    optionD: "bent",
    answer: "B",
  },
  {
    question: "I've got all the data. Now I just need to____the answer.",
    optionA: "make out",
    optionB: "count out",
    optionC: "think out",
    optionD: "work out",
    answer: "D",
  },
  {
    question:
      "They never argue and they enjoy spending time together. They____",
    optionA: "relate very well",
    optionB: "get on very well",
    optionC: "like themselves very much",
    optionD: "relationship very good",
    answer: "B",
  },
  {
    question: "I ____ swimming every Saturday morning.",
    optionA: "play",
    optionB: "do",
    optionC: "played",
    optionD: "go",
    answer: "D",
  },
  {
    question: "I didn't _____ going out tonight.",
    optionA: "want to",
    optionB: "have mood to",
    optionC: "feel like",
    optionD: "like",
    answer: "C",
  },
  {
    question: "She doesn't have brothers or sisters - she's____",
    optionA: "an only child",
    optionB: "an alone child",
    optionC: "a lonely child",
    optionD: "a single child",
    answer: "A",
  },
  {
    question:
      "I've been so busy all work. I don't want to do anything at the weekend - I'll stay at home and____.",
    optionA: "have a relax",
    optionB: "take it easy",
    optionC: "make it easy",
    optionD: "make a rest",
    answer: "B",
  },
  {
    question: "Do you want a____or a return ticket?",
    optionA: "single",
    optionB: "lonely",
    optionC: "outbound",
    optionD: "one-journey",
    answer: "A",
  },
  {
    question: "I love all fruit, but_____strawberries",
    optionA: "especially",
    optionB: "specially",
    optionC: "specifically",
    optionD: "mostly",
    answer: "A",
  },
  {
    question: "Breakfast. lunch and dinner are____",
    optionA: "food",
    optionB: "foodtimes",
    optionC: "meals",
    optionD: "eating",
    answer: "C",
  },
  {
    question:
      "I don't like my job very much. I'm going to____ and look for another one.",
    optionA: "retire",
    optionB: "fire",
    optionC: "resign",
    optionD: "finish",
    answer: "C",
  },
  {
    question: "Excuse me. I think you've _____ a mistake in our bill.",
    optionA: "made",
    optionB: "had",
    optionC: "given",
    optionD: "done",
    answer: "A",
  },
  {
    question: "I'm a bit lost. Can you tell me how to _____ to the university?",
    optionA: "get",
    optionB: "find",
    optionC: "go",
    optionD: "reach",
    answer: "A",
  },
  {
    question: "If I were you. I'd leave earlier, so you can avoid the _____",
    optionA: "peak pour",
    optionB: "traffic time",
    optionC: "rush hour",
    optionD: "peak time",
    answer: "C",
  },
  {
    question: "Choose the correct option.",
    optionA: "She will be writing the essay tomorrow.",
    optionB: "She had not wrote the essay by last Friday.",
    optionC: "She has not written the essay yet.",
    optionD: "She will have wrote the essay by Friday",
    answer: "A",
  },
];
